// File    : GridLayoutBehavior.cs
// Module  : Infrastructure / Behaviors
// Layer   : Presentation
// Purpose : Hai việc cho MỌI lưới DevExpress toàn app (gắn 1 lần qua implicit style dxg:TableView
//           trong Themes/Controls.xaml, không phải sửa từng màn):
//             1. Lưu & phục hồi FORMAT lưới (độ rộng / thứ tự / ẩn-hiện / sắp xếp cột) ra FILE LOCAL — KHÔNG đụng DB.
//             2. Ép CHÍNH SÁCH LỌC: hàng auto-filter luôn bật, cột text lọc kiểu "chứa" (Contains).
//
// Cơ chế  : - Mỗi lưới có 1 "profile key" tự sinh = {TênUserControl} + chữ ký cột (FieldName) → 1 file XML.
//           - Loaded  → nếu có file thì RestoreLayoutFromXml (áp lại độ rộng/vị trí người dùng đã chỉnh).
//           - Unloaded / thoát app → SaveLayoutToXml.
//           - File tại: %LOCALAPPDATA%\ICare247\ConfigStudio\GridLayouts\*.xml
//
// Vì sao phải ép lại chính sách lọc SAU khi restore (ADR ngầm — đừng gỡ):
//           RestoreLayoutFromXml khôi phục cả tuỳ chọn view lẫn bộ lọc đang lưu trong file.
//           File sinh ra TRƯỚC khi bật auto-filter chứa ShowAutoFilterRow=False → sẽ đè setter
//           trong Controls.xaml và làm hàng lọc "biến mất". Nên sau restore luôn gọi ApplyFilterPolicy.
//           Cũng vì thế bộ lọc KHÔNG được nhớ: mở lại lưới phải thấy ĐỦ dữ liệu, tránh người dùng
//           tưởng mất dữ liệu vì bộ lọc cũ còn sót.
//
// An toàn : Mọi lỗi I/O đều nuốt (Debug.WriteLine) — persistence layout KHÔNG bao giờ được làm crash app.

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using System.Windows;
using System.Windows.Media;
using DevExpress.Xpf.Grid;

namespace ConfigStudio.WPF.UI.Infrastructure.Behaviors;

/// <summary>
/// Attached behavior gắn lên <see cref="TableView"/>: tự lưu/phục hồi bố cục cột của
/// <see cref="GridControl"/> chủ ra file XML cục bộ (per-máy, không vào DB).
/// </summary>
public static class GridLayoutBehavior
{
    // ── Attached property bật/tắt ─────────────────────────────────────────────
    /// <summary>Bật persistence cho TableView (đặt qua implicit style).</summary>
    public static readonly DependencyProperty PersistProperty =
        DependencyProperty.RegisterAttached(
            "Persist", typeof(bool), typeof(GridLayoutBehavior),
            new PropertyMetadata(false, OnPersistChanged));

    public static void SetPersist(DependencyObject d, bool value) => d.SetValue(PersistProperty, value);
    public static bool GetPersist(DependencyObject d) => (bool)d.GetValue(PersistProperty);

    // Lưu profile key đã tính cho mỗi view (tránh tính lại + dùng khi Unloaded).
    private static readonly DependencyProperty ProfileKeyProperty =
        DependencyProperty.RegisterAttached(
            "ProfileKey", typeof(string), typeof(GridLayoutBehavior), new PropertyMetadata(null));

    // Các view đang sống — flush khi thoát app (Unloaded có thể không kịp khi đóng cửa sổ).
    private static readonly HashSet<TableView> LiveViews = new();
    private static bool _exitHooked;

    private static void OnPersistChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
    {
        if (d is not TableView view) return;

        if (e.NewValue is true)
        {
            view.Loaded += OnViewLoaded;
            view.Unloaded += OnViewUnloaded;
        }
        else
        {
            view.Loaded -= OnViewLoaded;
            view.Unloaded -= OnViewUnloaded;
        }
    }

    private static void OnViewLoaded(object sender, RoutedEventArgs e)
    {
        if (sender is not TableView view) return;
        if (view.DataControl is not GridControl grid) return;

        try
        {
            var key = view.GetValue(ProfileKeyProperty) as string;
            if (string.IsNullOrEmpty(key))
            {
                key = BuildProfileKey(grid);
                view.SetValue(ProfileKeyProperty, key);
            }

            HookAppExitOnce();
            LiveViews.Add(view);

            var path = PathFor(key!);
            if (File.Exists(path))
                grid.RestoreLayoutFromXml(path);
        }
        catch (Exception ex)
        {
            Debug.WriteLine($"[GridLayout] Restore failed: {ex.Message}");
            TryDeleteCorrupt(view);
        }

        // Ép lại chính sách lọc SAU restore (file cũ có thể mang ShowAutoFilterRow=False).
        // Cột chỉ biết FieldType khi đã có ItemsSource → nghe thêm 2 event để áp lại.
        ApplyFilterPolicy(view, grid, clearFilters: true);
        grid.ItemsSourceChanged -= OnGridItemsSourceChanged;
        grid.ItemsSourceChanged += OnGridItemsSourceChanged;
        grid.AutoGeneratedColumns -= OnGridAutoGeneratedColumns;
        grid.AutoGeneratedColumns += OnGridAutoGeneratedColumns;
    }

    private static void OnViewUnloaded(object sender, RoutedEventArgs e)
    {
        if (sender is TableView view)
        {
            SaveView(view);
            LiveViews.Remove(view);

            if (view.DataControl is GridControl grid)
            {
                grid.ItemsSourceChanged -= OnGridItemsSourceChanged;
                grid.AutoGeneratedColumns -= OnGridAutoGeneratedColumns;
            }
        }
    }

    private static void OnGridItemsSourceChanged(object sender, ItemsSourceChangedEventArgs e) => ReapplyFilterPolicy(sender);

    private static void OnGridAutoGeneratedColumns(object sender, RoutedEventArgs e) => ReapplyFilterPolicy(sender);

    // Nạp lại dữ liệu KHÔNG được xóa bộ lọc người dùng đang gõ → clearFilters=false.
    private static void ReapplyFilterPolicy(object sender)
    {
        if (sender is GridControl grid && grid.View is TableView view)
            ApplyFilterPolicy(view, grid, clearFilters: false);
    }

    // ── Chính sách lọc dùng chung cho MỌI lưới ────────────────────────────────
    /// <summary>
    /// Bật hàng lọc dưới header, cho phép đổi vị trí / giãn cột và gán điều kiện lọc "chứa"
    /// cho cột text. Khi <paramref name="clearFilters"/> = true (lúc mới mở lưới) thì xóa
    /// luôn bộ lọc vừa khôi phục từ file → lưới mở ra với ĐỦ dữ liệu.
    /// Gọi sau: RestoreLayoutFromXml, ItemsSourceChanged, ColumnsPopulated.
    /// </summary>
    private static void ApplyFilterPolicy(TableView view, GridControl grid, bool clearFilters)
    {
        try
        {
            view.ShowAutoFilterRow = true;
            view.AllowColumnFiltering = true;
            view.AllowColumnMoving = true;
            view.AllowResizing = true;

            foreach (var col in grid.Columns)
            {
                col.ImmediateUpdateAutoFilter = true;

                // Contains chỉ hợp lệ cho cột text. Cột số/ngày/bool giữ Default (so sánh bằng),
                // vì Contains trên kiểu không phải chuỗi không có nghĩa.
                var type = col.FieldType;
                var isText = type is null || type == typeof(string) || type == typeof(object);
                col.AutoFilterCondition = isText ? AutoFilterCondition.Contains : AutoFilterCondition.Default;

                if (clearFilters) col.AutoFilterValue = null;
            }

            // KHÔNG nhớ bộ lọc giữa các lần mở màn hình — chỉ nhớ format cột.
            if (clearFilters) grid.FilterCriteria = null;
        }
        catch (Exception ex)
        {
            Debug.WriteLine($"[GridLayout] ApplyFilterPolicy failed: {ex.Message}");
        }
    }

    private static void SaveView(TableView view)
    {
        if (view.DataControl is not GridControl grid) return;
        var key = view.GetValue(ProfileKeyProperty) as string;
        if (string.IsNullOrEmpty(key)) return;

        try
        {
            var dir = LayoutDir();
            Directory.CreateDirectory(dir);
            grid.SaveLayoutToXml(PathFor(key!));
        }
        catch (Exception ex)
        {
            Debug.WriteLine($"[GridLayout] Save failed: {ex.Message}");
        }
    }

    private static void HookAppExitOnce()
    {
        if (_exitHooked || Application.Current is null) return;
        _exitHooked = true;
        Application.Current.Exit += (_, _) =>
        {
            foreach (var v in LiveViews.ToArray())
                SaveView(v);
        };
    }

    private static void TryDeleteCorrupt(TableView view)
    {
        try
        {
            var key = view.GetValue(ProfileKeyProperty) as string;
            if (!string.IsNullOrEmpty(key))
            {
                var path = PathFor(key!);
                if (File.Exists(path)) File.Delete(path);
            }
        }
        catch { /* bỏ qua */ }
    }

    // ── Sinh key ổn định cho 1 lưới ───────────────────────────────────────────
    // Key = {TênUserControl chủ} + chữ ký cột. Hai lưới khác bộ cột (vd list vs editor)
    // trong cùng màn → khác file. Đổi tên/đổi cột → key đổi → layout reset (chấp nhận được).
    private static string BuildProfileKey(GridControl grid)
    {
        var owner = FindOwnerName(grid);
        var colSig = string.Join(",", grid.Columns.Select(c => c.FieldName ?? string.Empty));
        var disamb = !string.IsNullOrEmpty(grid.Name) ? "n:" + grid.Name : "c:" + colSig;
        return owner + "::" + disamb;
    }

    private static string FindOwnerName(DependencyObject start)
    {
        DependencyObject? cur = start;
        while (cur is not null)
        {
            if (cur is FrameworkElement fe && fe is System.Windows.Controls.UserControl)
                return cur.GetType().Name;
            cur = VisualTreeHelper.GetParent(cur)
                  ?? (cur is FrameworkElement f ? f.Parent : null);
        }
        return start.GetType().Name;
    }

    // ── Đường dẫn file ────────────────────────────────────────────────────────
    private static string LayoutDir() => Path.Combine(
        Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
        "ICare247", "ConfigStudio", "GridLayouts");

    private static string PathFor(string key)
    {
        // Tên file = phần đọc-được (tên UserControl) + hash ổn định của key đầy đủ.
        var readable = key.Split(new[] { "::" }, StringSplitOptions.None)[0];
        var safe = SanitizeFileName(readable);
        return Path.Combine(LayoutDir(), $"{safe}_{Fnv1a(key):x8}.xml");
    }

    private static string SanitizeFileName(string s)
    {
        var sb = new StringBuilder(s.Length);
        foreach (var ch in s)
            sb.Append(Array.IndexOf(Path.GetInvalidFileNameChars(), ch) >= 0 ? '_' : ch);
        return sb.Length == 0 ? "grid" : sb.ToString();
    }

    // FNV-1a 32-bit — hash ỔN ĐỊNH qua các lần chạy (KHÔNG dùng string.GetHashCode vì bị randomize).
    private static uint Fnv1a(string s)
    {
        const uint offset = 2166136261, prime = 16777619;
        uint hash = offset;
        foreach (var ch in s)
        {
            hash ^= ch;
            hash *= prime;
        }
        return hash;
    }
}
